# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Note: This file is only expected to be occasionally edited, consider using
# Jekyll's data files feature for any data you need to update frequently.

# site main title
title:              Your awesome title

# the base hostname & protocol for your site, e.g. http://example.com
url:                https://jekyll.github.io

# the subpath of your site, e.g. /blog
baseurl:            ""

# site info
author:             Jamie Osborne

# '>' ignore newlines until next setting
# description:        >
#                     write (multiline) description here

# permalink style to use for posts
# permalink:          /:title/

# custom marker to end excerpt
# excerpt_separator:  "\n\n\n"

# import theme
theme: minima

# theme settings
minima:
  date_format:      "%b %-d, %Y"
  # refer to http://shopify.github.io/liquid/filters/date/

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  show-rss:         yes
  twitter:          jmeosbn
  github:           jmeosbn
  linkedin:
  flickr:
  dribbble:
  facebook:
  instagram:
  pinterest:
  stackoverflow:    # users/50476/bart-kiers
  youtube:          # channel/<your_long_string> or user/<user-name>
  googleplus:       # username string that follows plus.google.com/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.html

# build settings
markdown:           kramdown
kramdown:
  input:            GFM
  hard_wrap:        false
  header_offset:    0
  toc_levels:       1..2
  auto_ids:         true
  entity_output:    as_char
  smart_quotes:     lsquo,rsquo,ldquo,rdquo

# sass :expanded or minify using :compressed
sass:
  style:            :compressed

# exclude files from production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# enable gems for offline build
gems:
  - jekyll-feed
  - jekyll-default-layout
